#!/usr/bin/env bash

#=======================
# PRINTING FN
#=======================

arrowPrint() {
    local VAL=${1}
    local BACKGROUND_COLOR=${2}
    local TEXT_COLOR

    # Set text color
    if [ -z ${3+x} ]; then 
        TEXT_COLOR="#f1f1f1";
    else 
        TEXT_COLOR=${3};
    fi

    echo "<span foreground='${BACKGROUND_COLOR}'></span><span foreground='${TEXT_COLOR}' background='${BACKGROUND_COLOR}'> ${VAL}   </span>"
}

#=======================
# BLOCKLET
#=======================

# Variables
#-----------------------
AUDIO_HIGH_SYMBOL=''
AUDIO_MED_SYMBOL=''
AUDIO_LOW_SYMBOL=''

AUDIO_MED_THRESH=50
AUDIO_LOW_THRESH=0

MUTED_TEXT_COLOR="#2a2a2a"
MUTED_BACKGROUND_COLOR="#a0a0a0"


# Mouse Buttons - L,M,R
#-----------------------
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
    amixer -q sset Master 5%+
elif [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
    amixer -q sset Master toggle
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
    amixer -q sset Master 5%-
fi


# Set Print Values
#-----------------------
statusLine=$(amixer get Master | tail -n 1)
status=$(echo "${statusLine}" | grep -wo "on")
volume=$(echo "${statusLine}" | awk -F ' ' '{print $5}' | tr -d '[]%')
intvol=$(expr ${volume})

if [ "${intvol}" -gt  0 ] && [ "${intvol}" -lt 34 ]; then
    AUDIO_SYMBOL="${AUDIO_LOW_SYMBOL}"
elif [ "${intvol}" -gt  34 ] && [ "${intvol}" -lt 64 ]; then
    AUDIO_SYMBOL="${AUDIO_MED_SYMBOL}"
elif [ "${intvol}" -gt  64 ]; then
    AUDIO_SYMBOL="${AUDIO_HIGH_SYMBOL}"
fi


# Print
#-----------------------
if [ "${status}" == "on" ] && [ "${volume}" != 0 ]; then
    arrowPrint "${AUDIO_SYMBOL} ${volume}%" '#f1f1f1' '#404040'
    arrowPrint "${AUDIO_SYMBOL} ${volume}%" '#f1f1f1' '#404040'
else
    arrowPrint "${AUDIO_LOW_SYMBOL}  OFF" '#fa4c4c' '#404040'
    arrowPrint "${AUDIO_LOW_SYMBOL}  OFF" '#fa4c4c' '#404040'
fi

