#!/usr/bin/env bash

#=======================
# PRINTING FN
#=======================

arrowPrint() {
    local VAL=${1}
    local BACKGROUND_COLOR=${2}
    local TEXT_COLOR

    # Set text color
    if [ -z ${3+x} ]; then 
        TEXT_COLOR="#ffffff";
    else 
        TEXT_COLOR=${3};
    fi

    echo "<span foreground='${BACKGROUND_COLOR}'></span><span foreground='${TEXT_COLOR}' background='${BACKGROUND_COLOR}'> ${VAL}   </span>"
}

#=======================
# BLOCKLET
#=======================
DATE_FORMAT="%a, %b %d"
DATE=$(date "+${DATE_FORMAT}")

# Print
#--------------------------------------
BACKGROUND_COLOR='#404040'
TEXT_COLOR='#f1f1f1'

echo "<span foreground='${BACKGROUND_COLOR}'></span><span foreground='${TEXT_COLOR}' background='${BACKGROUND_COLOR}'> ${DATE}   </span>"
echo "<span foreground='${BACKGROUND_COLOR}'></span><span foreground='${TEXT_COLOR}' background='${BACKGROUND_COLOR}'> ${DATE}   </span>"

