#!/usr/bin/env bash

#=======================
# PRINTING FN
#=======================

arrowPrint() {
    local VAL=${1}
    local BACKGROUND_COLOR=${2}
    local TEXT_COLOR

    # Set text color
    if [ -z ${3+x} ]; then 
        TEXT_COLOR="#ffffff";
    else 
        TEXT_COLOR=${3};
    fi

    echo "<span foreground='${BACKGROUND_COLOR}'></span><span foreground='${TEXT_COLOR}' background='${BACKGROUND_COLOR}'> ${VAL}   </span>"
}

#=======================
# BLOCKLET
#=======================
IP="$(wget -qO - icanhazip.com)"

# Copy to clipboard on mouse click
#--------------------------------------
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
    $(echo -n "${IP}" | xclip -sel clip) 
fi

# Print
#--------------------------------------
arrowPrint "${IP}" '#404040' '#f1f1f1'
arrowPrint "${IP}" '#404040' '#f1f1f1'
