#!/usr/bin/env bash

# ==================================
# INSTALL brewlist
# ==================================
echo -e "\nInstalling brewlist...\n\n"
cat brewlist.txt | xargs -L 1 brew install
echo -e "\nFinished installing brewlist.\n\n"

# ==================================
# INSTALL brewlist casks
# ==================================
echo -e "\nInstalling brewlist casks...\n\n"
cat brewlist.cask.txt | xargs -L 1 brew install --cask
echo -e "\nFinished installing brewlist casks.\n\n"

# ==================================
# INSTALL base16-manager
# ==================================
echo -e "Installing base16...\n\n"
brew tap chrokh/tap
brew install base16-manager
echo -e "\nFinished installing base16.\n\n"

echo "Done."

