#!/usr/bin/env bash

# HELPERS
# ----------------------------

link_mac_symlinks() {
    ln -sf ~/.dotfiles/bashrc/bashrc_mac ~/.bash_profile
    ln -sf ~/.dotfiles/bashrc/bashrc_mac ~/.bashrc
    ln -sf ~/.dotfiles/bashrc/bash_git_mac ~/.bash_git
    ln -sf ~/.dotfiles/bashrc/bash_aliases ~/.bash_aliases
    ln -sf ~/.dotfiles/gitconfig ~/.gitconfig
    ln -sf ~/.dotfiles/tmux.conf ~/.tmux.conf
    ln -sf ~/.dotfiles/ideavimrc ~/.ideavimrc
    ln -sf ~/.dotfiles/slate.js ~/.slate.js
#   ln -sf ~/.dotfiles/yabairc ~/.yabairc
#   ln -sf ~/.dotfiles/skhdrc ~/.skhdrc
}

link_linux_symlinks() {
    ln -sf ~/.dotfiles/bashrc/bashrc_linux ~/.bash_profile
    ln -sf ~/.dotfiles/bashrc/bashrc_linux ~/.bashrc
    ln -sf ~/.dotfiles/bashrc/bash_git_linux ~/.bash_git
    ln -sf ~/.dotfiles/bashrc/bash_aliases ~/.bash_aliases
    ln -sf ~/.dotfiles/gitconfig.linux ~/.gitconfig
    ln -sf ~/.dotfiles/tmux.conf.linux ~/.tmux.conf
}

setup_i3blocks() {
    sudo apt install fonts-font-awesome -y
    git clone https://github.com/Anachron/i3blocks.git tmp
    sudo cp -R tmp/blocks/. /usr/share/i3blocks
    rm -rf tmp
}

setup_tmux() {
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
}


# SETUP CONFIG
# ----------------------------
ln -sf ~/.dontfiles/config ~/.config


# INSTALL FOR SPECIFIC OS
# ----------------------------

if [ -z "${1}" ]; then
    echo "\n\tNeed to specify which OS, '-m' for Mac, '-l' for Linux\n"
    exit 1
elif [ "${1}" = "-m" ]; then
    link_mac_symlinks
    setup_tmux
elif [ "${1}" = "-l" ]; then
    link_linux_symlinks
    setup_i3blocks
    setup_tmux
else
    echo "\n\tValid flags for param are 'l' or 'm'\n"
    exit 1
fi


# FINISHED
# ----------------------------
echo "\nDone."

